#ifndef _EXTERNFILE_H_
#define _EXTERNFILE_H_


#define	PATH_BASE					"/m1000/"			//	主文件夹路径
#define	PATH_LOCAL					"/home/"
#define	PATH_DATA_					"/mnt/data/"

#define	PATH_DATA					".data/"			//	数据文件路径
#define	PATH_ICON					".icon/"			//	图片文件路径
#define	PATH_FONT					".font/"			//	字模文件路径
#define	PATH_LANG					".lan/"				//	语言文件路径

#define	PATH_BUTTON					"button/"			//	按键图片文件路径

#define	FILE_CFG_CONF				".conf"
#define	FILE_CFG_CONF_TMP			".conf~"
#define	FILE_CFG_NET				".netcfg"

#define	PROGRAM_VTKEYBOART			"Ctrl"
#define	PROGRAM_M1000				"m1000"

#define	FILE_DATA_FETAL				"fetal.bin"
#define	FILE_DATA_DATA				"data."

#define	BUTTON_PAGEUP				"left.bmp"
#define	BUTTON_PAGEDN				"right.bmp"
#define	BUTTON_RECORD				"record.bmp"
#define	BUTTON_SYSCFG				"config.bmp"
#define	BUTTON_FACE					"face.bmp"
#define	ICON_AC						"AC.bmp"
#define	ICON_BATT					"battery.bmp"
#define	ICON_NOBATT					"nobattery.bmp"
#define	ICON_LOBATT					"battery-lo.bmp"
#define	ICON_NET					"network.bmp"
#define	ICON_NONET					"nonetwork.bmp"
#define ICON_ULNET					"network_ul.bmp"
#define	ICON_PRINT					"printer.bmp"
#define	ICON_NOPRINT				"noprinter.bmp"
#define	ICON_VOL					"vol.bmp"
#define	ICON_VOL_MUTE				"vol-mute.bmp"
#define	ICON_VOL_LO					"vol-lo.bmp"
#define	ICON_VOL_MID				"vol-mid.bmp"
#define	ICON_VOL_HI					"vol-hi.bmp"
#define	ICON_FULL					"battery_full.bmp"
#define	ICON_ALARM					"alarm.bmp"
#define	ICON_DISALARM				"disableAlarm.bmp"

#define	NIGHT_BUTTON_PAGEUP			"left_night.bmp"
#define	NIGHT_BUTTON_PAGEDN			"right_night.bmp"
#define	NIGHT_BUTTON_RECORD			"record_night.bmp"
#define	NIGHT_BUTTON_SYSCFG			"config_night.bmp"
#define	NIGHT_BUTTON_FACE			"face_night.bmp"
#define	NIGHT_ICON_AC				"AC_night.bmp"
#define	NIGHT_ICON_BATT				"battery_night.bmp"
#define	NIGHT_ICON_NOBATT			"nobattery_night.bmp"
#define	NIGHT_ICON_LOBATT			"battery-lo_night.bmp"
#define	NIGHT_ICON_NET				"network_night.bmp"
#define	NIGHT_ICON_NONET			"nonetwork_night.bmp"
#define NIGHT_ICON_ULNET			"network_ul_night.bmp"
#define	NIGHT_ICON_PRINT			"printer_night.bmp"
#define	NIGHT_ICON_NOPRINT			"noprinter_night.bmp"
#define	NIGHT_ICON_VOL				"vol_night.bmp"
#define	NIGHT_ICON_VOL_MUTE			"vol-mute_night.bmp"
#define	NIGHT_ICON_VOL_LO			"vol-lo_night.bmp"
#define	NIGHT_ICON_VOL_MID			"vol-mid_night.bmp"
#define	NIGHT_ICON_VOL_HI			"vol-hi_night.bmp"
#define	NIGHT_ICON_FULL				"battery_full_night.bmp"
#define	NIGHT_ICON_ALARM			"alarm_night.bmp"
#define	NIGHT_ICON_DISALARM			"disableAlarm_night.bmp"

#define	FILE_FONT_HZK12				"HZK12.bin"
#define	FILE_FONT_HZK16				"HZK16.bin"
#define	FILE_FONT_YH17				"YH17.bin"

#define	FILE_LAN_ZH_CN				"zh_CN.lan"
#define	FILE_LAN_EN_US				"en_US.lan"
#define	FILE_LAN_RU_RU				"ru_RU.lan"
#define	FILE_LAN_ES_ES				"es_ES.lan"
#define	FILE_LAN_TR_TR				"tr_TR.lan"

#ifdef  PATH_BASE
#define FILEPATH	PATH_BASE
#else
#define FILEPATH	PATH_LOCAL
#endif

#define	FILEPATH_FONT		FILEPATH	PATH_FONT
#define	FILEPATH_LANG		FILEPATH	PATH_LANG
#define	FILEPATH_ICON		FILEPATH	PATH_ICON	PATH_ICON
#define	FILEPATH_BUTTON		FILEPATH	PATH_ICON	PATH_BUTTON
#define	FILEPATH_DATA		PATH_DATA_//FILEPATH	PATH_DATA

#define	FPP_M1000			FILEPATH	PROGRAM_M1000
#define	FPP_KEY				FILEPATH	PROGRAM_VTKEYBOART
#define	FPC_CONFIG			FILEPATH	FILE_CFG_CONF
#define	FPC_TMPCFG			FILEPATH	FILE_CFG_CONF_TMP
#define	FPC_NETCFG			FILEPATH	FILE_CFG_NET

#define	FPF_HZK12			FILEPATH_FONT	FILE_FONT_HZK12
#define	FPF_HZK16			FILEPATH_FONT	FILE_FONT_HZK16
#define	FPF_YH17			FILEPATH_FONT	FILE_FONT_YH17

#define	FPL_ZH_CN			FILEPATH_LANG	FILE_LAN_ZH_CN
#define	FPL_EN_US			FILEPATH_LANG	FILE_LAN_EN_US
#define	FPL_RU_RU			FILEPATH_LANG	FILE_LAN_RU_RU
#define	FPL_ES_ES			FILEPATH_LANG	FILE_LAN_ES_ES
#define	FPL_TR_TR			FILEPATH_LANG	FILE_LAN_TR_TR

#define	FPB_PAGEUP			FILEPATH_BUTTON	BUTTON_PAGEUP
#define	FPB_PAGEDN			FILEPATH_BUTTON	BUTTON_PAGEDN
#define	FPB_RECORD			FILEPATH_BUTTON	BUTTON_RECORD
#define	FPB_SYSCFG			FILEPATH_BUTTON	BUTTON_SYSCFG
#define	FPB_FACE			FILEPATH_BUTTON	BUTTON_FACE
#define	FPB_PAGEUP_N		FILEPATH_BUTTON	NIGHT_BUTTON_PAGEUP
#define	FPB_PAGEDN_N		FILEPATH_BUTTON	NIGHT_BUTTON_PAGEDN
#define	FPB_RECORD_N		FILEPATH_BUTTON	NIGHT_BUTTON_RECORD
#define	FPB_SYSCFG_N		FILEPATH_BUTTON	NIGHT_BUTTON_SYSCFG
#define	FPB_FACE_N			FILEPATH_BUTTON	NIGHT_BUTTON_FACE

#define	FPI_AC				FILEPATH_ICON	ICON_AC
#define	FPI_BATT			FILEPATH_ICON	ICON_BATT
#define	FPI_NOBATT			FILEPATH_ICON	ICON_NOBATT
#define	FPI_LOBATT			FILEPATH_ICON	ICON_LOBATT
#define	FPI_NET				FILEPATH_ICON	ICON_NET
#define	FPI_NONET			FILEPATH_ICON	ICON_NONET
#define FPI_ULNET			FILEPATH_ICON	ICON_ULNET
#define	FPI_PRINT			FILEPATH_ICON	ICON_PRINT
#define	FPI_NOPRINT			FILEPATH_ICON	ICON_NOPRINT
#define	FPI_VOL				FILEPATH_ICON	ICON_VOL
#define	FPI_VOL_MUTE		FILEPATH_ICON	ICON_VOL_MUTE
#define	FPI_VOL_LO			FILEPATH_ICON	ICON_VOL_LO
#define	FPI_VOL_MID			FILEPATH_ICON	ICON_VOL_MID
#define	FPI_VOL_HI			FILEPATH_ICON	ICON_VOL_HI
#define	FPI_FULL			FILEPATH_ICON	ICON_FULL
#define	FPI_ALARM			FILEPATH_ICON	ICON_ALARM
#define	FPI_DISALARM		FILEPATH_ICON	ICON_DISALARM
#define	FPI_AC_N			FILEPATH_ICON	NIGHT_ICON_AC
#define	FPI_BATT_N			FILEPATH_ICON	NIGHT_ICON_BATT
#define	FPI_NOBATT_N		FILEPATH_ICON	NIGHT_ICON_NOBATT
#define	FPI_LOBATT_N		FILEPATH_ICON	NIGHT_ICON_LOBATT
#define	FPI_NET_N			FILEPATH_ICON	NIGHT_ICON_NET
#define	FPI_NONET_N			FILEPATH_ICON	NIGHT_ICON_NONET
#define FPI_ULNET_N			FILEPATH_ICON	NIGHT_ICON_ULNET
#define	FPI_PRINT_N			FILEPATH_ICON	NIGHT_ICON_PRINT
#define	FPI_NOPRINT_N		FILEPATH_ICON	NIGHT_ICON_NOPRINT
#define	FPI_VOL_N			FILEPATH_ICON	NIGHT_ICON_VOL
#define	FPI_VOL_MUTE_N		FILEPATH_ICON	NIGHT_ICON_VOL_MUTE
#define	FPI_VOL_LO_N		FILEPATH_ICON	NIGHT_ICON_VOL_LO
#define	FPI_VOL_MID_N		FILEPATH_ICON	NIGHT_ICON_VOL_MID
#define	FPI_VOL_HI_N		FILEPATH_ICON	NIGHT_ICON_VOL_HI
#define	FPI_FULL_N			FILEPATH_ICON	NIGHT_ICON_FULL
#define	FPI_ALARM_N			FILEPATH_ICON	NIGHT_ICON_ALARM
#define	FPI_DISALARM_N		FILEPATH_ICON	NIGHT_ICON_DISALARM

#define	FPD_FETAL			FILEPATH_DATA	FILE_DATA_FETAL
#define	FPD_DATA			FILEPATH_DATA	FILE_DATA_DATA

#define SYS24BMP_PAGEUP					FPB_PAGEUP
#define SYS24BMP_PAGEDN					FPB_PAGEDN
#define SYS24BMP_RECORD					FPB_RECORD
#define SYS24BMP_SYSCFG					FPB_SYSCFG
#define SYS24BMP_FACE					FPB_FACE
#define SYS24BMP_ICON_AC				FPI_AC
#define SYS24BMP_ICON_BATT				FPI_BATT
#define SYS24BMP_ICON_NOBATT			FPI_NOBATT
#define SYS24BMP_ICON_LOBATT			FPI_LOBATT
#define SYS24BMP_ICON_NET				FPI_NET
#define SYS24BMP_ICON_NONET				FPI_NONET
#define SYS24BMP_ICON_ULNET				FPI_ULNET
#define SYS24BMP_ICON_PRINT				FPI_PRINT
#define SYS24BMP_ICON_NOPRINT			FPI_NOPRINT
#define SYS24BMP_ICON_VOL				FPI_VOL
#define SYS24BMP_ICON_VOL_MUTE			FPI_VOL_MUTE
#define SYS24BMP_ICON_VOL_LO			FPI_VOL_LO
#define SYS24BMP_ICON_VOL_MID			FPI_VOL_MID
#define SYS24BMP_ICON_VOL_HI			FPI_VOL_HI
#define SYS24BMP_ICON_FULL				FPI_FULL
#define SYS24BMP_ICON_ALARM				FPI_ALARM
#define SYS24BMP_DISABLEALARM			FPI_DISALARM

#define SYS24BMP_NIGHT_PAGEUP			FPB_PAGEUP_N
#define SYS24BMP_NIGHT_PAGEDN			FPB_PAGEDN_N
#define SYS24BMP_NIGHT_RECORD			FPB_RECORD_N
#define SYS24BMP_NIGHT_SYSCFG			FPB_SYSCFG_N
#define SYS24BMP_NIGHT_FACE				FPB_FACE_N
#define SYS24BMP_NIGHT_ICON_AC			FPI_AC_N
#define SYS24BMP_NIGHT_ICON_BATT		FPI_BATT_N
#define SYS24BMP_NIGHT_ICON_NOBATT		FPI_NOBATT_N
#define SYS24BMP_NIGHT_ICON_LOBATT		FPI_LOBATT_N
#define SYS24BMP_NIGHT_ICON_NET			FPI_NET_N
#define SYS24BMP_NIGHT_ICON_NONET		FPI_NONET_N
#define SYS24BMP_NIGHT_ICON_ULNET		FPI_ULNET_N
#define SYS24BMP_NIGHT_ICON_PRINT		FPI_PRINT_N
#define SYS24BMP_NIGHT_ICON_NOPRINT		FPI_NOPRINT_N
#define SYS24BMP_NIGHT_ICON_VOL			FPI_VOL_N
#define SYS24BMP_NIGHT_ICON_VOL_MUTE	FPI_VOL_MUTE_N
#define SYS24BMP_NIGHT_ICON_VOL_LO		FPI_VOL_LO_N
#define SYS24BMP_NIGHT_ICON_VOL_MID		FPI_VOL_MID_N
#define SYS24BMP_NIGHT_ICON_VOL_HI		FPI_VOL_HI_N
#define SYS24BMP_NIGHT_ICON_FULL		FPI_FULL_N
#define SYS24BMP_NIGHT_ICON_ALARM		FPI_ALARM_N
#define SYS24BMP_NIGHT_DISABLEALARM		FPI_DISALARM_N

#endif /*_EXTERNFILE_H_*/

