/*
******************************************************************************** 
*								
*		   (c) Copyright 2005, TM Electronic Technology, Inc.
* 
* All rights reserved. TM’s source code is an unpublished work and the 
* use of a copyright notice does not imply otherwise. This source code contains 
* confidential, trade secret material of TM, Inc. Any attempt or participation 
* in deciphering, decoding, reverse engineering or in any way altering the source 
* code is strictly prohibited, unless the prior written consent of TM is obtained. 
* 
* Filename :	 winstr.c
* Programmer(s): eric 
*				 
* Created :   2005/10/10 
* Description : 
*
* History:
*	 Name		  Date			   Remark
*	 eric		  2005/10/10		 Created initial version 1.0
******************************************************************************** 
*/

#include  "includes.h"
#define WINSTR_GLOBALS

char gMonitorUUID[37];
//CHAR  **GlobalStr;
CHAR  * GlobalStr[STR_MAXNUM];

static CHAR MapString[STR_MAXNUM][150];
#define LAN_ZH_CN FPL_ZH_CN
#define LAN_EN_US FPL_EN_US
#define LAN_RU_RU FPL_RU_RU	 //Russian
#define LAN_ES_ES FPL_ES_ES	 //castellano
#define LAN_TR_TR FPL_TR_TR	 //Turkish

const static unsigned char StrID_Key[STR_MAXNUM][36] = {
	 "STR_NULL"
	
	,"STR_SWITCH_ON"
	,"STR_SWITCH_OFF"
	
	,"STR_LEVEL_HIGH"
	,"STR_LEVEL_MIDDLE"
	,"STR_LEVEL_LOW"
	
	,"STR_AUTO"
	
	,"STR_WEEK_SUNDAY"
	,"STR_WEEK_MONDAY"
	,"STR_WEEK_TUESDAY"
	,"STR_WEEK_WEDNESDAY"
	,"STR_WEEK_THURSDAY"
	,"STR_WEEK_FIRDAY"
	,"STR_WEEK_SATURDAY"
	
	,"STR_ARROW_HOME"
	,"STR_ARROW_BACK"
	,"STR_ARROW_LEFT"
	,"STR_ARROW_RIGHT"
	,"STR_ARROW_FORWARD"
	,"STR_ARROW_END"
	,"STR_MAIN_TOPBAR_NAME_STR"
	,"STR_MAIN_TOPBAR_NAME_NAME"
	,"STR_MAIN_TOPBAR_ID_STR"
	,"STR_MAIN_TOPBAR_ID_NUM"
	,"STR_MAIN_PATIENT_INFO1"
	,"STR_MAIN_PATIENT_INFO2"
	,"STR_MAIN_PATIENT_INFO3"
	,"STR_MAIN_TOPBAR_ALARM_TECH"
	,"STR_MAIN_TOPBAR_ALARM_LVL"
	,"STR_MAIN_TOPBAR_ALARM_INFO"
	,"STR_MAIN_TOPBAR_ALARM_DATE"
	,"STR_MAIN_TOPBAR_ALARM_TIME"
	,"STR_MAIN_BOTTOM_HELP_INFO"
	,"STR_MAIN_BOTTOM_DATE"
	,"STR_MAIN_BOTTOM_TIME"
	,"STR_MAIN_BOTTOM_WEEK"
	,"STR_MAIN_BOTTOM_FACE"
	,"STR_MAIN_BOTTOM_NEWPATIENT"
	,"STR_MAIN_BOTTOM_SILENCE"
	,"STR_MAIN_BOTTOM_RECALL"
	,"STR_MAIN_BOTTOM_SYSTEM_CONFIG"
	,"STR_MAIN_BOTTOM_SAVE"
	,"STR_MAIN_BOTTOM_REMAIN"
	,"STR_MAIN_BOTTOM_ELAPSE"
	,"STR_MAIN_BOTTOM_PERIOD"
	,"STR_MAIN_BOTTOM_SAVE_TIME"
	,"STR_MAIN_BOTTOM_ELAPSE_TIME"
	,"STR_MAIN_BOTTOM_PERIOD_TIME"
	
	,"STR_MAIN_PARAM_FHR1"
	,"STR_MAIN_PARAM_FHR1_VAL"
	,"STR_MAIN_PARAM_FHR2"
	,"STR_MAIN_PARAM_FHR2_VAL"
	,"STR_MAIN_PARAM_TOCO"
	,"STR_MAIN_PARAM_TOCO_VAL"
	,"STR_MAIN_PARAM_FETALMOVE"
	,"STR_MAIN_PARAM_FM"
	,"STR_MAIN_PARAM_FM_VAL"
	,"STR_MAIN_PARAM_AFM"
	,"STR_MAIN_PARAM_AFM_VAL"
	
	,"STR_MSGBOX_DEF_CAPTION"
	,"STR_MSGBOX_COMPANY"
	,"STR_MSGBOX_OK"
	,"STR_MSGBOX_CANCEL"
	,"STR_MSGBOX_PREVIOUS"
	,"STR_MSGBOX_BACK"
	,"STR_MSGBOX_NEXT"
	,"STR_MSGBOX_CONFIRM_YES"
	,"STR_MSGBOX_CONFIRM_NO"
	,"STR_MSGBOX_RETRY"
	,"STR_MSGBOX_ABORT"
	,"STR_MSGBOX_IGNORE"
	,"STR_MSGBOX_CAP_SYSTEM_POWEROFF"
	,"STR_MSGBOX_PRO_SYSTEM_POWEROFF1"
	,"STR_MSGBOX_PRO_SYSTEM_POWEROFF2"
	
	,"STR_MSGBOX_CAP_SYSTEM_SETTIME"
	,"STR_MSGBOX_PRO_SYSTEM_SETTIME"
	
	,"STR_MSGBOX_CAP_FMSETZERO"
	,"STR_MSGBOX_PRO_FMSETZERO"
	
	,"STR_MSGBOX_PRO_CONFIRM_ANALYSIS1"
	,"STR_MSGBOX_PRO_CONFIRM_ANALYSIS2"
	
	,"STR_MSGBOX_PRO_ANALY"
	
	,"STR_MSGBOX_CAP_DELFILE"
	,"STR_MSGBOX_PRO_DELFILE"
	,"STR_MSGBOX_CAP_AUTOPRINT"
	,"STR_MSGBOX_PRO_AUTOPRINT"
	
	,"STR_MSGBOX_SYSTEM_INFO"
	,"STR_MSGBOX_PRO_TOUCHCAL_ERROR"
	,"STR_MSGBOX_PRO_TOUCHCAL_CONTINUE"
	,"STR_MSGBOX_PRO_NOT_TOUCH_CALC"
	,"STR_MSGBOX_PRO_ENTER_TOUCH_CALC"
	,"STR_MSGBOX_PRO_DEFAULT_CONFIG"
	,"STR_PRINT_TYPE_FETAL"
	,"STR_PRINT_TYPE_REACLL"
	,"STR_PRINT_TYPE_PAGE"
	,"STR_PRINT_TYPE_ALL"
	,"STR_PRINT_TIME_START"
	,"STR_PRINT_TIME_END"
	,"STR_PRINT_TIME_TIMING"
	,"STR_PRINT_TIME_LENGTH"
	,"STR_PRINT_NAME"
	,"STR_PRINT_ID"
	,"STR_PRINT_AGE"
	,"STR_PRINT_WEEK"
	,"STR_PRINT_TIMES"
	,"STR_PRINT_NOTE"
	,"STR_DLG_PAGE_HOME"
	,"STR_DLG_PAGE_UP"
	,"STR_DLG_PAGE_DOWN"
	,"STR_DLG_PAGE_END"
	,"STR_DLG_MOVE_LEFT"
	,"STR_DLG_MOVE_RIGHT"
	,"STR_DLG_CLOSE"
	,"STR_DLG_EXIT"
	,"STR_DlG_TECH_ALM"
	,"STR_DlG_PHYS_ALM"
	,"STR_DLG_FHR_SETUP"
	,"STR_DLG_ALARM_SWITCH"
	,"STR_DLG_ALM_LVL"
	,"STR_DLG_FHR_ALM_HI"
	,"STR_DLG_FHR_ALM_LO"
	,"STR_DLG_FHR_SOURCE"
	,"STR_DLG_FHR_VOLUME"
	,"STR_DLG_FHR_DETACH_SPLINE"
	,"STR_DLG_FHR_TYPE"
	,"STR_DLG_FHR_FHR1"
	,"STR_DLG_FHR_FHR2"
	,"STR_DLG_FHR_SINGLE"
	,"STR_DLG_FHR_DOUBLE"
	,"STR_DLG_TOCO_SETUP"
	,"STR_DLG_TOCO_ZERO"
	,"STR_DLG_TOCO_ZERO_VAL"
	,"STR_DLG_TOCO_ZERO_00"
	,"STR_DLG_TOCO_ZERO_05"
	,"STR_DLG_TOCO_ZERO_10"
	,"STR_DLG_TOCO_ZERO_15"
	,"STR_DLG_TOCO_ZERO_20"
	,"STR_DLG_FM_SETUP"
	,"STR_DLG_FM_THRESHOLD"
	,"STR_DLG_FM_THRESHOLD10"
	,"STR_DLG_FM_THRESHOLD20"
	,"STR_DLG_FM_THRESHOLD30"
	,"STR_DLG_FM_THRESHOLD40"
	,"STR_DLG_FM_THRESHOLD50"
	,"STR_DLG_FM_THRESHOLD60"
	,"STR_DLG_FM_THRESHOLD70"
	,"STR_DLG_FM_THRESHOLD80"
	,"STR_DLG_FM_MOVEMENTCAL"
	,"STR_DLG_FM_MOVEMENTCAL_AUTO"
	,"STR_DLG_FM_MOVEMENTCAL_MANUAL"
	,"STR_DLG_FM_MOVEMENTCAL_BOTH"
	,"STR_DLG_FM_MOVEMENT_ZERO"
	
	
	,"STR_DLG_DRM_BTN"
	,"STR_DLG_DRM_TITLE"
	,"STR_DLG_DRM_A"
	,"STR_DLG_DRM_B"
	,"STR_DLG_DRM_C"
	,"STR_DLG_DRM_D"
	,"STR_DLG_DRM_E"
	,"STR_DLG_DRM_F"
	,"STR_DLG_DRM_G"
	,"STR_DLG_DRM_H"
	,"STR_DLG_DRM_I"
	,"STR_DLG_DRM_J"
	,"STR_DLG_DRM_K"
	,"STR_DLG_DRM_L"
	,"STR_DLG_DRM_M"
	,"STR_DLG_DRM_N"
	,"STR_DLG_DRM_O"
	
	,"STR_DLG_FHR_DIAG_ACC_NORMAL"
	,"STR_DLG_FHR_DIAG_ACC_LITTLE"
	,"STR_DLG_FHR_DIAG_ACC_FASTIGIA"
	,"STR_DLG_FHR_DIAG_REDUCE_SLOW"
	,"STR_DLG_FHR_DIAG_REDUCE_LITTLE"
	,"STR_DLG_FHR_DIAG_REDUCE_SLOW_TAIL"
	,"STR_DLG_FHR_DIAG_REDUCE_VARY_SLOW"
	,"STR_DLG_FHR_DIAG_REDUCE_HEAVY_VARY"
	,"STR_DLG_FHR_DIAG_REDUCE_LIGHT_VARY"
	,"STR_DLG_FHR_DIAG_REDUCE_EARLY"
	,"STR_DLG_FHR_DIAG_REDUCE_EXTEND"
	,"STR_DLG_FHR_DIAG_REDUCE_EARLY_VARY" 
	
	,"STR_SWEEP_SPEED_1"
	,"STR_SWEEP_SPEED_2"
	,"STR_SWEEP_SPEED_3"
	
	,"STR_DLG_PATIENT_SETUP"
	,"STR_DLG_PATIENT_INFO"
	,"STR_DLG_PATIENT_NAME"
	,"STR_DLG_PATIENT_NAME_NAME"
	,"STR_DLG_PATIENT_ID"
	,"STR_DLG_PATIENT_ID_ID"
	,"STR_DLG_PATIENT_AGE"
	,"STR_DLG_PATIENT_AGE_DLG"
	,"STR_DLG_PATIENT_AGE_AGE"
	,"STR_DLG_PATIENT_GESTATIONAL"
	,"STR_DLG_PATIENT_GESTATIONAL_DLG"
	
	,"STR_DLG_PATIENT_GESTATIONAL_WEEK"
	,"STR_DLG_PATIENT_GESTATIONAL_DAY"

	,"STR_DLG_PATIENT_GESTATIONAL_WEEK_UNIT"//
	,"STR_DLG_PATIENT_GESTATIONAL_DAY_UNIT"

	
	,"STR_DLG_PATIENT_GTIMES"
	,"STR_DLG_PATIENT_GTIMES_DLG"
	,"STR_DLG_PATIENT_GTIMES_TIMES"
	,"STR_DLG_PATIENT_NOTE"
	,"STR_DLG_PATIENT_NOTE_PAD"
	,"STR_DLG_PATIENT_EDIT"
	,"STR_DLG_PATIENT_SAVE"
	,"STR_DLG_PATIENT_LIST_NAME"
	,"STR_DLG_PATIENT_LIST_ID"
	,"STR_DLG_PATIENT_LIST_TIME"
	,"STR_DLG_PATIENT_LIST_ITEM0"
	,"STR_DLG_PATIENT_LIST_ITEM1"
	,"STR_DLG_PATIENT_LIST_ITEM2"
	,"STR_DLG_PATIENT_LIST_ITEM3"
	,"STR_DLG_PATIENT_LIST_ITEM4"
	,"STR_DLG_PATIENT_LIST_ITEM5"
	,"STR_DLG_PATIENT_LIST_ITEM6"
	,"STR_DLG_PATIENT_LIST_ITEM7"
	,"STR_DLG_PATIENT_LIST_ITEM8"
	,"STR_DLG_PATIENT_LIST_ITEM9"
	
	,"STR_DLG_NEW_PATIENT"
	,"STR_DLG_NEW_PATIENT_OTHER"
	,"STR_DLG_NEW_PATIENT_INFO"
	,"STR_DLG_NEW_PATIENT_CANCEL"
	,"STR_DLG_NEW_PATIENT_BACK"
	,"STR_DLG_NEW_PATIENT_NEXT"
	,"STR_DLG_NEW_PATIENT_BUILD"
	,"STR_DLG_NEW_PATIENT_WARNING1"
	,"STR_DLG_NEW_PATIENT_WARNING2"
	,"STR_DLG_NEW_PATIENT_WARNING3"
	
	,"STR_DLG_PNT_RECALL_MANAGER"
	,"STR_DLG_PNT_RECALL_ALL"
	,"STR_DLG_PNT_RECALL_NAME"
	,"STR_DLG_PNT_RECALL_ID"
	,"STR_DLG_PNT_RECALL_OPEN"
	,"STR_DLG_PNT_RECALL_DELETE"
	,"STR_DLG_PNT_RECALL_PNAME0"
	,"STR_DLG_PNT_RECALL_PNAME1"
	,"STR_DLG_PNT_RECALL_PNAME2"
	,"STR_DLG_PNT_RECALL_PNAME3"
	,"STR_DLG_PNT_RECALL_PNAME4"
	,"STR_DLG_PNT_RECALL_PNAME5"
	,"STR_DLG_PNT_RECALL_PNAME6"
	,"STR_DLG_PNT_RECALL_PNAME7"
	,"STR_DLG_PNT_RECALL_PNAME8"
	,"STR_DLG_PNT_RECALL_PNAME9"
	,"STR_DLG_PNT_RECALL_PID0"
	,"STR_DLG_PNT_RECALL_PID1"
	,"STR_DLG_PNT_RECALL_PID2"
	,"STR_DLG_PNT_RECALL_PID3"
	,"STR_DLG_PNT_RECALL_PID4"
	,"STR_DLG_PNT_RECALL_PID5"
	,"STR_DLG_PNT_RECALL_PID6"
	,"STR_DLG_PNT_RECALL_PID7"
	,"STR_DLG_PNT_RECALL_PID8"
	,"STR_DLG_PNT_RECALL_PID9"
	
	,"STR_DLG_RECALL_CAPTION"
	,"STR_DLG_RECALL_TIME"
	,"STR_DLG_RECALL_INFO"
	,"STR_DLG_RECALL_ENDTIME"
	,"STR_DLG_RECALL_LENGTH"
	,"STR_DLG_RECALL_PRINT_PAGE"
	,"STR_DLG_RECALL_PRINT_ALL"
	
	,"STR_DLG_CHAR_A"
	,"STR_DLG_CHAR_B"
	,"STR_DLG_CHAR_C"
	,"STR_DLG_CHAR_D"
	,"STR_DLG_CHAR_E"
	,"STR_DLG_CHAR_F"
	,"STR_DLG_CHAR_G"
	,"STR_DLG_CHAR_H"
	,"STR_DLG_CHAR_I"
	,"STR_DLG_CHAR_J"
	,"STR_DLG_CHAR_K"
	,"STR_DLG_CHAR_L"
	,"STR_DLG_CHAR_M"
	,"STR_DLG_CHAR_N"
	,"STR_DLG_CHAR_O"
	,"STR_DLG_CHAR_P"
	,"STR_DLG_CHAR_Q"
	,"STR_DLG_CHAR_R"
	,"STR_DLG_CHAR_S"
	,"STR_DLG_CHAR_T"
	,"STR_DLG_CHAR_U"
	,"STR_DLG_CHAR_V"
	,"STR_DLG_CHAR_W"
	,"STR_DLG_CHAR_X"
	,"STR_DLG_CHAR_Y"
	,"STR_DLG_CHAR_Z"
	,"STR_DLG_CHAR_0"
	,"STR_DLG_CHAR_1"
	,"STR_DLG_CHAR_2"
	,"STR_DLG_CHAR_3"
	,"STR_DLG_CHAR_4"
	,"STR_DLG_CHAR_5"
	,"STR_DLG_CHAR_6"
	,"STR_DLG_CHAR_7"
	,"STR_DLG_CHAR_8"
	,"STR_DLG_CHAR_9"
	,"STR_DLG_CHAR_SPACE"
	,"STR_DLG_CHAR_DEL"
	,"STR_DLG_CHAR_OK"
	,"STR_DLG_CHAR_ESC"
	,"STR_DLG_CHAR_MINUS"
	,"STR_DLG_CHAR_DOT"
	,"STR_DLG_CHAR_NUM_MARK"
	,"STR_DLG_CHAR_IME"
	,"STR_DLG_CHAR_MARK"
	,"STR_DLG_CHAR_COMMA"
	,"STR_DLG_CHAR_CAPS"
	,"STR_DLG_KB_PY_PRE"
	,"STR_DLG_KB_PY_NEXT"
	,"STR_DLG_KB_PY_CHAR1"
	,"STR_DLG_KB_PY_CHAR2"
	,"STR_DLG_KB_PY_CHAR3"
	,"STR_DLG_KB_PY_CHAR4"
	,"STR_DLG_KB_PY_CHAR5"
	,"STR_DLG_KB_PY_CHAR6"
	,"STR_DLG_KB_PY_CHAR7"
	,"STR_DLG_KB_PY_CHAR8"
	,"STR_DLG_KB_CAPTION"
	,"STR_DLG_KB_INPUT"
	,"STR_DLG_KB_TIPS"
	,"STR_DLG_PASSWD_OK"
	,"STR_DLG_PASSWD_CANCEL"
	,"STR_DLG_PASSWD_CAPTION"
	,"STR_DLG_PASSWD1_CAPTION"
	,"STR_DLG_PASSWD2_CAPTION"
	,"STR_DLG_PASSWD3_CAPTION"
	,"STR_DLG_PASSWD4_CAPTION"
	,"STR_DLG_PASSWD_TIPS"
	,"STR_DLG_PASSWD_ERROR"
	,"STR_DLG_SETDATETIME"
	,"STR_DLG_SETDATE"
	,"STR_DLG_SETTIME"
	,"STR_DLG_SETUP"
	,"STR_DLG_SETUP_FETAL"
	,"STR_DLG_SETUP_PRINT"
	,"STR_DLG_SETUP_PRINTER"
	,"STR_DLG_SETUP_SYSTEM"
	,"STR_DLG_SETUP_DATETIME"
	,"STR_DLG_SETUP_ALARM"
	
	,"STR_DLG_SETUP_ALM_VOL"
	,"STR_DLG_SETUP_KEY_VOL"
	,"STR_DLG_SETUP_FASTPRINT"
	,"STR_DLG_SETUP_SPEED"
	,"STR_DLG_SETUP_TIMER"
	,"STR_DLG_SETUP_AUTOPRINT"
	,"STR_DLG_SETUP_PRINTTYPE"
	,"STR_DLG_SETUP_PRINTCONTRAST"
	
	,"STR_DLG_SETUP_SET_FM"
	,"STR_DLG_SETUP_PRINT_B"
	,"STR_DLG_SETUP_PRINTER_B"
	,"STR_DLG_SETUP_NETWORK_B"
	,"STR_DLG_SETUP_NETWORK"
	,"STR_DLG_SETUP_DEMO"
	,"STR_DLG_SETUP_DEMO_EXIT"
	
	,"STR_DLG_SETUP_PRINT_PAGE"
	,"STR_DLG_SETUP_PRINT_PAGESTART"
	,"STR_DLG_SETUP_PRINT_CURR"
	
	,"STR_DLG_SETUP_DEFAULT"
	
	,"STR_DLG_NIGHT_MODE"
	,"STR_DLG_EXIT_NIGHT_MODE"
	
	,"STR_DLG_NET_AUTOLINK"
	,"STR_DLG_NET_IPADDR"
	,"STR_DLG_NET_MASK"
	,"STR_DLG_NET_GATEWAY"
	,"STR_DLG_NET_SERVERIP"
	,"STR_DLG_NET_PORT"
	,"STR_DLG_NET_HWADDR"
	,"STR_DLG_NET_SERVER"
	
	,"STR_DLG_ANALY_FUNC"
	,"STR_DLG_ANALY_VALID"
	,"STR_DLG_ANALY_COLLECT"
	,"STR_DLG_ANALY_BUILD"
	,"STR_DLG_ANALY_AUTO"
	,"STR_DLG_ANALY_RESTART"
	,"STR_DLG_ANALY_DONE"
	,"STR_DLG_ANALY_SHOW"
	,"STR_DLG_ANALY_RESULT"
	,"STR_DLG_ANALY_SAVE"
	,"STR_DLG_ANALY_PRINT"
	,"STR_DLG_ANLS_ITEMS"
	,"STR_DLG_ANLS_FHR_BASE"
	,"STR_DLG_ANLS_AMPLITUDE"
	,"STR_DLG_ANLS_FAST_TIME"
	,"STR_DLG_ANLS_FAST_AMPL"
	,"STR_DLG_ANLS_FM_TIMES"
	,"STR_DLG_ANLS_RESULT"
	,"STR_DLG_ANLS_SCORE"
	,"STR_DLG_ANLS_NAME"
	,"STR_DLG_ANLS_TIME"
	,"STR_DLG_ANLS_VALID"
	,"STR_DLG_ANLS_TOCO"
	,"STR_DLG_ANLS_ANALYSIS_RESULT"
	,"STR_DLG_ANLS_DIAGNOSIS"
	,"STR_DLG_ANLS_DATAONLYREFERENCE"
	,"STR_DLG_ANLS_SIGNATURE"
	,"STR_DLG_ANLS_DATE"
	
	,"STR_DLG_05MIN"
	,"STR_DLG_10MIN"
	,"STR_DLG_15MIN"
	,"STR_DLG_20MIN"
	,"STR_DLG_30MIN"
	,"STR_DLG_40MIN"
	,"STR_DLG_50MIN"
	,"STR_DLG_60MIN"
	,"STR_DLG_50PERCENT"
	,"STR_DLG_75PERCENT"
	,"STR_DLG_100PERCENT"
	
	,"STR_DLG_PRINTER_FHR60"
	,"STR_DLG_PRINTER_FHR210"
	,"STR_DLG_PRINTER_FHRMIN"
	,"STR_DLG_PRINTER_FHRMAX"
	,"STR_DLG_PRINTER_TOCO100"
	,"STR_DLG_PRINTER_TOCO0"
	,"STR_DLG_PRINTER_SCALE"
	,"STR_DLG_PRINTER_SELFTEST"
	,"STR_DLG_PRINTER_30"
	,"STR_DLG_PRINTER_60"
	,"STR_DLG_PRINTER_90"
	,"STR_DLG_PRINTER_180"
	,"STR_DLG_PRINTER_210"
	,"STR_DLG_PRINTER_240"
	
	,"STR_DLG_STATUS"
	,"STR_DLG_STATUS_INFO1"
	,"STR_DLG_STATUS_INFO2"
	,"STR_DLG_STATUS_INFO3"
	,"STR_DLG_STATUS_INFO4"
	,"STR_DLG_STATUS_INFO5"
	,"STR_DLG_STATUS_INFO6"
	,"STR_DLG_STATUS_INFO7"
	,"STR_DLG_STATUS_INFO8"
	,"STR_DLG_STATUS_INFO9"
	
	,"STR_DLG_STATUS_AC"
	,"STR_DLG_STATUS_DC"
	,"STR_DLG_STATUS_CHARGING"
	,"STR_DLG_STATUS_FULLCHARGED"
	,"STR_DLG_STATUS_NOBATT"
	,"STR_DLG_STATUS_BATTPOWER"
	,"STR_DLG_STATUS_NETWORKRUNNING"
	,"STR_DLG_STATUS_NETWORKDISCONN"
	,"STR_DLG_STATUS_PRINTER"
	,"STR_DLG_STATUS_ALARM"
	
	,"STR_DLG_SYSSETUP"
	,"STR_DLG_SYSSETUP_B"
	,"STR_DLG_SYSSETUP_COLOR"
	,"STR_DLG_SYSSETUP_COLOR_B"
	,"STR_DLG_SYSSETUP_LANGUAGE"
	,"STR_DLG_SYSSETUP_LANGUAGE_B"

	,"STR_DLG_LANGUAGE_CHOICE"
	,"STR_DLG_DATE_FORMAT"
	,"STR_DLG_DATE_DELIMITER"
	,"STR_DLG_TIME_FORMAT"
	,"STR_DLG_LANGUAGE_ENGLISH"
	,"STR_DLG_LANGUAGE_CHINESE"
	,"STR_DLG_LANGUAGE_RUSSIAN"
	,"STR_DLG_LANGUAGE_SPANISH"
	,"STR_DLG_LANGUAGE_TURKISH"
	,"STR_DLG_DATE_FORMAT_YMD"
	,"STR_DLG_DATE_FORMAT_MDY"
	,"STR_DLG_DATE_FORMAT_DMY"
	,"STR_DLG_DATE_FORMAT_HMS"
	,"STR_DLG_DATE_FORMAT_HM"
	,"STR_DLG_DATE_FORMAT_THMS"
	,"STR_DLG_DATE_FORMAT_THM"
	,"STR_DLG_DATE_DELIMITER1"
	,"STR_DLG_DATE_DELIMITER2"
	,"STR_DLG_DATE_DELIMITER3"
	
	,"STR_DLG_FACTORY_MAINTAIN_B"
	,"STR_DLG_FACTORY_MAINTAIN"
	,"STR_DLG_FACTORY_MONITORTYPE"
	,"STR_DLG_FACTORY_ARTEMIS4S"
	,"STR_DLG_FACTORY_ARTEMIS2"
	,"STR_DLG_FACTORY_ARTEMIS4S_DLG"
	,"STR_DLG_FACTORY_ARTEMIS2_DLG"
	,"STR_DLG_FACTORY_ENBTOUCH"
	,"STR_DLG_FACTORY_RECORDERTYPE"
	,"STR_DLG_FACTORY_REC_112"
	,"STR_DLG_FACTORY_REC_150"
	,"STR_DLG_FACTORY_REC_SETUP"
	,"STR_DLG_FACTORY_UPDATE"
	,"STR_DLG_FACTORY_ANALY_ENABLE"
	,"STR_DLG_FACTORY_ANALY_DISABLE"
	,"STR_DLG_FACTORY_VERSION"
	,"STR_DLG_FACTORY_TOCORESET"

	,"STR_DLG_ABOUT_B"
	,"STR_DLG_ABOUT"
	,"STR_DLG_ABOUT_TIME"
	,"STR_DLG_ABOUT_START"
	,"STR_DLG_ABOUT_VERSION"
	,"STR_DLG_ABOUT_VERSION_NUM"
	,"STR_DLG_ABOUT_COMPILE_TIME"
	,"STR_DLG_ABOUT_COMPILE_DATE"
	,"STR_DLG_ABOUT_COMPANY"
	
	,"STR_DLG_COLOR"
	,"STR_DLG_MAINTAIN_B"
	,"STR_DLG_MAINTAIN"
	,"STR_ENABLE_HELP_STRING"
	,"STR_DISABLE_HELP_STRING"
	
	
	,"STR_ALM_FHR1_TOO_HI"
	,"STR_ALM_FHR1_TOO_LO"
	,"STR_ALM_FHR2_TOO_HI"
	,"STR_ALM_FHR2_TOO_LO"
	
	,"STR_ALM_FETAL_INIT_ERROR"
	,"STR_ALM_FHR1_LOW_SIGNAL"
	,"STR_ALM_FHR2_LOW_SIGNAL"
	,"STR_ALM_FETAL_COMM_ERR"
	,"STR_ALM_FETAL_COMM_STOP"
	,"STR_ALM_FHR_ALM_LMT_ERR"
	,"STR_ALM_FHR1_EXCEED"
	,"STR_ALM_FHR2_EXCEED"
	,"STR_ALM_TOCO_EXCEED"
	,"STR_ALM_FHR1_SENSOR_OFF"
	,"STR_ALM_FHR2_SENSOR_OFF"
	,"STR_ALM_TOCO_SENSOR_OFF"
	,"STR_ALM_FM_SENSOR_OFF"
	,"STR_ALM_KEYBOARD_INIT_ERR"
	,"STR_ALM_KEYBOARD_NOT_AVAILABLE"
	,"STR_ALM_KEYBOARD_COMM_ERR"
	,"STR_ALM_POWER_5V_TOO_HIGH"
	,"STR_ALM_POWER_5V_TOO_LOW"
	,"STR_ALM_POWER_12V_TOO_HIGH"
	,"STR_ALM_POWER_12V_TOO_LOW"
	,"STR_ALM_POWER_3V_TOO_HIGH"
	,"STR_ALM_POWER_3V_TOO_LOW"
	,"STR_ALM_POWER_BATTERY_LOW"
	,"STR_ALM_BATTREY_20_MINUTES"
	,"STR_ALM_BATTREY_10_MINUTES"
	,"STR_ALM_BATTERY_VOL_TOO_HIGH"
	,"STR_ALM_BATTERY_VOL_TOO_LOW"
	,"STR_ALM_PRINTER_HIGH_CURRENT"
	,"STR_ALM_PRINTER_HEAD_HOT"
	,"STR_ALM_PRINTER_DOOR_NOT_CLOSED"
	,"STR_ALM_PRINTER_PAPER_OUT"
	,"STR_ALM_PRINTER_SERIAL_ERR"
	,"STR_ALM_PRINTER_NOT_AVAILABLE"
	,"STR_ALM_TECH_MAX"
	,"STR_HELP_TECH_ALARM_INFO"
	,"STR_HELP_PHYS_ALARM_INFO"
	,"STR_HELP_SYSTEM_STATUS"
	,"STR_HELP_PATIENT_SETUP"
	,"STR_HELP_CHANGE_FACE"
	,"STR_HELP_SYSTEM_MENU"
	,"STR_HELP_DATETIME_SETUP"
	,"STR_HELP_ENTER_VIEW_WAVE"
	,"STR_HELP_EXIT_VIEW_WAVE"
	,"STR_HELP_FETAL_WAVE_MOVE_LEFT"
	,"STR_HELP_FETAL_WAVE_MOVE_RIGHT"
	,"STR_REC_FIRST"
	,"STR_DLG_ANLS_BASE_LINE"
	,"STR_DLG_ANLS_AMPLITUDE_VAR"
	,"STR_DLG_ANLS_PERIOD_VAR"
	,"STR_DLG_ANLS_ACCELRATION"
	,"STR_DLG_ANLS_SLOWDOWN"
	,"STR_DLG_ANLS_SLOWDOWN_TYPE0"
	,"STR_DLG_ANLS_SLOWDOWN_TYPE1"
	,"STR_DLG_ANLS_SLOWDOWN_TYPE2"
	,"STR_DLG_ANLS_ACCELRATION_TYPE0"
	,"STR_DLG_ANLS_ACCELRATION_TYPE1"
	,"STR_DLG_ANLS_ACCELRATION_TYPE2"
	,"STR_DLG_ANLS_NST"
	,"STR_DLG_ANLS_FISCHER"
	,"STR_DLG_ANLS_KREBS"
	,"STR_DLG_ANLS_CST"
	,"STR_DLG_ANLS_FETALMOVIE"
	,"STR_DLG_ANLS_NOTHING"
	,"STR_DLG_ANLS_NOTHINGORED"
	,"STR_DLG_ANLS_LDOROTHER"
	,"STR_DLG_ANLS_CHANGE"
	,"STR_DLG_ANLS_EDSLOW"
	,"STR_DLG_ANLS_LASTSLOW"
};

VOID LoadLanFileByStrIdKey(UCHAR *buffer)
{
	UCHAR *pBuff;
	UCHAR *p;
	INT32 i;
	pBuff = buffer;
	// 跳过空格和缩进
	while(*pBuff == ' ' || *pBuff == '\t' || *pBuff == '\r')
	{
		pBuff++;
	}
	// 跳过注释符号和空行
	if (*pBuff == ';' || *pBuff == '#' || *pBuff == '\'' || *pBuff == '\n')
	{
		return;
	}
	for (i = 0; i < STR_MAXNUM; i++)
	{
		p = pBuff;
		if (0 == memcmp(p, StrID_Key[i], strlen((char*)StrID_Key[i])))//memcmp效率高于strcmp
		{
			p = p + strlen((char*)StrID_Key[i]);
			while(*p == ' ' || *p == '\t')
			{
				p++;
			}
			if (*p++ != '=')
			{
				continue;
			}
			if (strlen((char*)p) < sizeof(MapString[i]))
			{
				strcpy(MapString[i], (char*)p);
				// 处理换行字符
				p = (UCHAR*)&MapString[i][strlen((char*)p) - 1];
				if (*p == '\r' || *p == '\n')
				{
					*p-- = '\0';
					if (*p == '\r' || *p == '\n')
					{
						*p = '\0';
					}
				}
			}
			break;
		}
	}
}

BOOL LoadLanguage(INT8 language)
{
	extern char en_us_string[STR_MAXNUM][150];
	extern char zh_cn_string[STR_MAXNUM][150];
	extern char ru_ru_string[STR_MAXNUM][150];

	FILE *fp;
	switch (language)
	{
		case ENGLISH:
			memcpy(MapString[0], en_us_string[0], sizeof(MapString));
			return TRUE;;
			fp = fopen(LAN_EN_US, "rb");
			if (!fp)
			{
				return FALSE;
			}
			break;

		case CHINESE:
			memcpy(MapString[0], zh_cn_string[0], sizeof(MapString));
			return TRUE;;
			fp = fopen(LAN_ZH_CN, "rb");
			if (!fp)
			{
				return FALSE;
			}
			break;

		case RUSSIAN:
			memcpy(MapString[0], ru_ru_string[0], sizeof(MapString));
			return TRUE;;

			fp = fopen(LAN_RU_RU, "rb");
			if (!fp)
			{
				return FALSE;
			}
			break;

		case SPANISH:
			fp = fopen(LAN_ES_ES, "rb");
			if (!fp)
			{
				return FALSE;
			}
			break;

		case TURKISH:
			fp = fopen(LAN_TR_TR, "rb");
			if (!fp)
			{
				return FALSE;
			}
			break;

		default:
			return FALSE;
	}
	UCHAR *buff;
	UCHAR *temp;
	
	if (NULL == (buff = TextNew(MAX_STR_LENGTH)))
	{
		printf("LoadLanguage:Can't malloc buffer!\n");
		fclose(fp);
		return FALSE;
	}
	memset(&MapString[0][0], '\0', sizeof(MapString));
	while(NULL !=(temp = (UCHAR*)fgets((char*)buff, MAX_STR_LENGTH, fp)))
	{
		LoadLanFileByStrIdKey(temp);
	}
	fclose(fp);
	TextDel(buff);
	return TRUE;
}

void ChangeMonitorName(void)
{
	char *txt = LoadString(STR_DLG_ABOUT);
	char *src = LoadString(STR_DLG_ABOUT_B);
	char *value = LoadString(STR_DLG_FACTORY_ARTEMIS4S_DLG
		+ (MonitorConfig.MonitorName & 0x01));
	char *p;
	strcpy(txt, src);
	p = strchr(txt, '>');
	if (p == NULL)
	{
		p = txt;
	}
	strcpy(p, value);
}


BOOL  InitGlobalString (INT8 language)
{
	int i;
	//MonitorConfig.language = CHINESE;
	if (!LoadLanguage(MonitorConfig.language))
		return FALSE;
	for (i = 0; i < STR_MAXNUM; i++)
	{
		GlobalStr[i] = MapString[i];
	}
	ChoiceFont(MonitorConfig.language);
	ChangeMonitorName();
	return TRUE;
}


BOOL  ReInitGlobalStrPtr (INT8 language)
{
	if (!LoadLanguage(MonitorConfig.language))
		return FALSE;
	ChoiceFont(MonitorConfig.language);
	ChangeMonitorName();

	strcpy(LoadString(STR_MAIN_TOPBAR_NAME_NAME), PatientInfo.patientName);
	strcpy(LoadString(STR_MAIN_TOPBAR_ID_NUM), PatientInfo.patientID);
	return TRUE;
}

/*
	本函数仅用于复制小于1MB的文件,不能复制过大的文件
*/
BOOL CopySmallFile(const char *src, const char *dest)
{
	BOOL ret = FALSE;
	if (CheckFileExist(src))
	{
		UINT32 len;
		char *buf;
		if (NULL != (buf = (char*)LoadSmallFile(src, &len)))
		{
			FILE *fp = fopen(dest, "wb");
			if (fp)
			{
				if (fwrite(buf, len, 1, fp))
				{
					ret = TRUE;
				}
				fclose(fp);
			}
			free(buf);
		}
	}
	return ret;
}

extern const UCHAR LanguageAkaName[MAX_LANGUAGE][6][8];
static char lanName[MAX_LANGUAGE][12] = {
	FILE_LAN_EN_US,
	FILE_LAN_ZH_CN,
	FILE_LAN_RU_RU,
	FILE_LAN_ES_ES,
	FILE_LAN_TR_TR
};

BOOL CheckExternLanguageFile(LANGUAGE lan, const char *dir_src)
{
	char buf[128] = {0};
	char *src = buf;
	char *dest = buf + sizeof(buf) / 2;
	BOOL ret = FALSE;
	sprintf(src, "%s/%s", dir_src, lanName[lan]);
	sprintf(dest, "/tmp/%s", lanName[lan]);
	if (CopySmallFile(src, dest))
	{
		FILE *fp = fopen(dest, "rb");
		char *temp;
		while(NULL != (temp = fgets(buf, sizeof(buf), fp)))
		{
			if (*temp == ';' || *temp == '#' || *temp == '\'' || *temp == '\n')
			{
				continue;
			}
			if (*temp == '[')
			{
				temp++;
				if (0 == memcmp(temp, LanguageAkaName[lan][1],
					strlen((char*)LanguageAkaName[lan][1])))
				{
					ret = TRUE;
				}
			}
			break;
		}
		fclose(fp);
	}
	if (!ret)
	{
		sprintf(dest, "/tmp/%s", lanName[lan]);
		remove(dest);
	}
	return ret;
}

VOID GetLanguageFile(const char *dir_src)
{
	int i;
	for (i = 0; i < MAX_LANGUAGE; i++)
	{
		CheckExternLanguageFile(i, dir_src);
	}
}

BOOL SaveLanguageFile(INT8 lan)
{
	char src[32];
	char dest[32];
	if (MAX_LANGUAGE == lan)
	{
		int i;
		char num = 0;
		for (i = 0; i < MAX_LANGUAGE; i++)
		{
			sprintf(src, "/tmp/%s", lanName[i]);
			sprintf(dest, "%s%s", FILEPATH_LANG, lanName[i]);
			if (CopySmallFile(src, dest))
			{
				if (0 == remove(src))
					num++;
			}
		}
		return (num > 0);
	}
	else
	{
		sprintf(src, "/tmp/%s", lanName[lan]);
		sprintf(dest, "%s%s", FILEPATH_LANG, lanName[lan]);
		if (CopySmallFile(src, dest))
		{
			if (0 == remove(src))
				return TRUE;
		}
		return FALSE;
	}
}


