/*
******************************************************************************** 
*								
*		   (c) Copyright 2005, TM Electronic Technology, Inc.
* 
* All rights reserved. TM’s source code is an unpublished work and the 
* use of a copyright notice does not imply otherwise. This source code contains 
* confidential, trade secret material of TM, Inc. Any attempt or participation 
* in deciphering, decoding, reverse engineering or in any way altering the source 
* code is strictly prohibited, unless the prior written consent of TM is obtained. 
* 
* Filename :	 winstr.h
* Programmer(s): eric 
*				 
* Created :   2005/10/10 
*
* Description : 
*		系统程序中所有字符串id号
*		由于字符串很多;在这里定义时,必须制定一些规则;对字符串进行分类,便于以后的
*  维护;
*		目前的分类:
*		  通用类,包括菜单,对话框,热键,界面,提示的字符串;
*		  报警类,所有生理报警,技术报警,nibp报警用的字符串;
*		  帮助类,所有空间,菜单,对话框的帮助信息;
*		  记录类,所有记录用的字符串
*		所有大类的字符前面都有特殊注释 @@@@@XXXX,  XXXX一般是大的模块,比如报警,
*  帮助,记录等.( ALARM, HELP, REC)
*		以后增加字符串,必须首先判定属于那一个大类,然后添加到该类的最后;原则上不许
*  删去以前定义过的字符串;即使不再用到;
*		这里定义的字符串id号,在设计不具备某些次序规则;因此,外部模块引用时不应该
*  假设它们的定义次序是不变的;不得依赖于本文件中id大小次序;应自己定义规则和次序.
*		字符串id编制的规则:
*		   STR_DLG_xxxxx,	用在对话框中的字符串,包括message box
*		   STR_HK_xxxxx,	 用在热键
*		   STR_MENU_xxxxx,   用在菜单中
*		   STR_ALM_xxxxx,	用在报警
*		   STR_HELP_xxxxx,   用在帮助
*		   STR_REC_xxxxx,	用在记录
*		   STR_INFO_xxxx,	用在提示信息
*		   STR_EVE_xxxxx,	用在系统事件的记录
*		   STR_NET_xxxxx,	用在网络
*		   STR_ML_xxxxx,	 用在多语言
*
*   为了便于查找, 在注释中增加特殊字符序列: $$##XXXX, xxxx表示对象,它可以是菜单,
*   功能名称.
*
* History:
*	 Name		  Date			   Remark
*	 eric		  2005/10/10		 Created initial version 1.0
******************************************************************************** 
*/
#if !defined(_WINCTRL_H)
#define	_WINCTRL_H

#define STR_VERSION			10	// string resource version 1.0
#define MAX_STR_LENGTH		512	// The Max string length used.

// string resource, 字符串资源
typedef struct  _global_string_res
{
   INT16  index;
   INT16  maxLen;
   CHAR   text[150];
} GLOBAL_STRING_RES;

typedef enum  _string_id {
	/* ****通用字符串-开始 ****** */
	
	/******所有菜单中的字符串******/
	
	// $$##系统菜单中的字符串
	STR_NULL,		 /*第一个字符串,为空字符, 不要引用它. */

	/* define universal string	  {{{ */
	STR_SWITCH_ON,
	STR_SWITCH_OFF,
	
	STR_LEVEL_HIGH,
	STR_LEVEL_MIDDLE,
	STR_LEVEL_LOW,

	STR_AUTO,
	
	STR_WEEK_SUNDAY,
	STR_WEEK_MONDAY,
	STR_WEEK_TUESDAY,
	STR_WEEK_WEDNESDAY,
	STR_WEEK_THURSDAY,
	STR_WEEK_FIRDAY,
	STR_WEEK_SATURDAY,
	
	STR_ARROW_HOME,
	STR_ARROW_BACK,
	STR_ARROW_LEFT,
	STR_ARROW_RIGHT,
	STR_ARROW_FORWARD,
	STR_ARROW_END,
	/* }}} end define universal string  */

	/* define top-bar string		{{{ */
	STR_MAIN_TOPBAR_NAME_STR,
	STR_MAIN_TOPBAR_NAME_NAME,
	STR_MAIN_TOPBAR_ID_STR,
	STR_MAIN_TOPBAR_ID_NUM,
	STR_MAIN_PATIENT_INFO1,
	STR_MAIN_PATIENT_INFO2,
	STR_MAIN_PATIENT_INFO3,
	STR_MAIN_TOPBAR_ALARM_TECH,
	STR_MAIN_TOPBAR_ALARM_LVL,
	STR_MAIN_TOPBAR_ALARM_INFO,
	STR_MAIN_TOPBAR_ALARM_DATE,
	STR_MAIN_TOPBAR_ALARM_TIME,
	/* }}} end define top-bar string	*/

	/* define bottom-bar string	 {{{ */
	STR_MAIN_BOTTOM_HELP_INFO,
	STR_MAIN_BOTTOM_DATE,
	STR_MAIN_BOTTOM_TIME,
	STR_MAIN_BOTTOM_WEEK,
	STR_MAIN_BOTTOM_FACE,
	STR_MAIN_BOTTOM_NEWPATIENT,
	STR_MAIN_BOTTOM_SILENCE,
	STR_MAIN_BOTTOM_RECALL,
	STR_MAIN_BOTTOM_SYSTEM_CONFIG,
	STR_MAIN_BOTTOM_SAVE,
	STR_MAIN_BOTTOM_REMAIN,
	STR_MAIN_BOTTOM_ELAPSE,
	STR_MAIN_BOTTOM_PERIOD,
	STR_MAIN_BOTTOM_SAVE_TIME,
	STR_MAIN_BOTTOM_ELAPSE_TIME,
	STR_MAIN_BOTTOM_PERIOD_TIME,
	/* }}} end define bottom-bar string */

	STR_MAIN_PARAM_FHR1,
	STR_MAIN_PARAM_FHR1_VAL,
	STR_MAIN_PARAM_FHR2,
	STR_MAIN_PARAM_FHR2_VAL,
	STR_MAIN_PARAM_TOCO,
	STR_MAIN_PARAM_TOCO_VAL,
	STR_MAIN_PARAM_FETALMOVE,
	STR_MAIN_PARAM_FM,
	STR_MAIN_PARAM_FM_VAL,
	STR_MAIN_PARAM_AFM,
	STR_MAIN_PARAM_AFM_VAL,

	//// System Message string,for messagebox
	//// STR_MSGBOX_CAP:message box caption;STR_MSGBOX_PRO:message box prompt
	//// define Message string
	STR_MSGBOX_DEF_CAPTION,
	STR_MSGBOX_COMPANY,
	STR_MSGBOX_OK,
	STR_MSGBOX_CANCEL,
	STR_MSGBOX_PREVIOUS,
	STR_MSGBOX_BACK,
	STR_MSGBOX_NEXT,
	STR_MSGBOX_CONFIRM_YES,
	STR_MSGBOX_CONFIRM_NO,
	STR_MSGBOX_RETRY,
	STR_MSGBOX_ABORT,
	STR_MSGBOX_IGNORE,
	STR_MSGBOX_CAP_SYSTEM_POWEROFF,
	STR_MSGBOX_PRO_SYSTEM_POWEROFF1,
	STR_MSGBOX_PRO_SYSTEM_POWEROFF2,

	STR_MSGBOX_CAP_SYSTEM_SETTIME,
	STR_MSGBOX_PRO_SYSTEM_SETTIME,

	STR_MSGBOX_CAP_FMSETZERO,
	STR_MSGBOX_PRO_FMSETZERO,

	STR_MSGBOX_PRO_CONFIRM_ANALYSIS1,
	STR_MSGBOX_PRO_CONFIRM_ANALYSIS2,

	STR_MSGBOX_PRO_ANALY,

	STR_MSGBOX_CAP_DELFILE,
	STR_MSGBOX_PRO_DELFILE,
	STR_MSGBOX_CAP_AUTOPRINT,
	STR_MSGBOX_PRO_AUTOPRINT,

	STR_MSGBOX_SYSTEM_INFO,
	STR_MSGBOX_PRO_TOUCHCAL_ERROR,
	STR_MSGBOX_PRO_TOUCHCAL_CONTINUE,
	STR_MSGBOX_PRO_NOT_TOUCH_CALC,
	STR_MSGBOX_PRO_ENTER_TOUCH_CALC,
	STR_MSGBOX_PRO_DEFAULT_CONFIG,
	//// end define Message string

	//// define print string
	STR_PRINT_TYPE_FETAL,
	STR_PRINT_TYPE_REACLL,
	STR_PRINT_TYPE_PAGE,
	STR_PRINT_TYPE_ALL,
	STR_PRINT_TIME_START,
	STR_PRINT_TIME_END,
	STR_PRINT_TIME_TIMING,
	STR_PRINT_TIME_LENGTH,
	STR_PRINT_NAME,
	STR_PRINT_ID,
	STR_PRINT_AGE,
	STR_PRINT_WEEK,
	STR_PRINT_TIMES,
	STR_PRINT_NOTE,
	//// end define print string

	//// define dialog string


	//// define dialog common string {{{
	STR_DLG_PAGE_HOME,
	STR_DLG_PAGE_UP,
	STR_DLG_PAGE_DOWN,
	STR_DLG_PAGE_END,
	STR_DLG_MOVE_LEFT,
	STR_DLG_MOVE_RIGHT,
	STR_DLG_CLOSE,
	STR_DLG_EXIT,
	//// }}} end define dialog common string

	STR_DlG_TECH_ALM,
	STR_DlG_PHYS_ALM,

	//// define fhr setup dialog string {{{
	STR_DLG_FHR_SETUP,
	STR_DLG_ALARM_SWITCH,
	STR_DLG_ALM_LVL,
	STR_DLG_FHR_ALM_HI,
	STR_DLG_FHR_ALM_LO,
	STR_DLG_FHR_SOURCE,
	STR_DLG_FHR_VOLUME,
	STR_DLG_FHR_DETACH_SPLINE,
	STR_DLG_FHR_TYPE,
	STR_DLG_FHR_FHR1,
	STR_DLG_FHR_FHR2,
	STR_DLG_FHR_SINGLE,
	STR_DLG_FHR_DOUBLE,
	//// }}} end define fhr setup dialog string

	//// define toco setup dialog string {{{
	STR_DLG_TOCO_SETUP,
	STR_DLG_TOCO_ZERO,
	STR_DLG_TOCO_ZERO_VAL,
	STR_DLG_TOCO_ZERO_00,
	STR_DLG_TOCO_ZERO_05,
	STR_DLG_TOCO_ZERO_10,
	STR_DLG_TOCO_ZERO_15,
	STR_DLG_TOCO_ZERO_20,
	//// }}} end define toco setup dialog string

	//// define fm setup dialog string {{{
	STR_DLG_FM_SETUP,
	STR_DLG_FM_THRESHOLD,
	STR_DLG_FM_THRESHOLD10,
	STR_DLG_FM_THRESHOLD20,
	STR_DLG_FM_THRESHOLD30,
	STR_DLG_FM_THRESHOLD40,
	STR_DLG_FM_THRESHOLD50,
	STR_DLG_FM_THRESHOLD60,
	STR_DLG_FM_THRESHOLD70,
	STR_DLG_FM_THRESHOLD80,
	STR_DLG_FM_MOVEMENTCAL,
	STR_DLG_FM_MOVEMENTCAL_AUTO,
	STR_DLG_FM_MOVEMENTCAL_MANUAL,
	STR_DLG_FM_MOVEMENTCAL_BOTH,
	STR_DLG_FM_MOVEMENT_ZERO,
	//// }}} end define fm setup dialog string

	
#if 1
	STR_DLG_DRM_BTN,
	STR_DLG_DRM_TITLE,
	STR_DLG_DRM_A,
	STR_DLG_DRM_B,
	STR_DLG_DRM_C,
	STR_DLG_DRM_D,
	STR_DLG_DRM_E,
	STR_DLG_DRM_F,
	STR_DLG_DRM_G,
	STR_DLG_DRM_H,
	STR_DLG_DRM_I,
	STR_DLG_DRM_J,
	STR_DLG_DRM_K,
	STR_DLG_DRM_L,
	STR_DLG_DRM_M,
	STR_DLG_DRM_N,
	STR_DLG_DRM_O,

	//自动诊断及评分字符串
	STR_DLG_FHR_DIAG_ACC_NORMAL,
	STR_DLG_FHR_DIAG_ACC_LITTLE,
	STR_DLG_FHR_DIAG_ACC_FASTIGIA,
	STR_DLG_FHR_DIAG_REDUCE_SLOW,
	STR_DLG_FHR_DIAG_REDUCE_LITTLE,
	STR_DLG_FHR_DIAG_REDUCE_SLOW_TAIL,
	STR_DLG_FHR_DIAG_REDUCE_VARY_SLOW,
	STR_DLG_FHR_DIAG_REDUCE_HEAVY_VARY,
	STR_DLG_FHR_DIAG_REDUCE_LIGHT_VARY,
	STR_DLG_FHR_DIAG_REDUCE_EARLY,
	STR_DLG_FHR_DIAG_REDUCE_EXTEND,
	STR_DLG_FHR_DIAG_REDUCE_EARLY_VARY, 
#endif
	
	STR_SWEEP_SPEED_1,
	STR_SWEEP_SPEED_2,
	STR_SWEEP_SPEED_3,

	STR_DLG_PATIENT_SETUP,
	STR_DLG_PATIENT_INFO,
	STR_DLG_PATIENT_NAME,
	STR_DLG_PATIENT_NAME_NAME,
	STR_DLG_PATIENT_ID,
	STR_DLG_PATIENT_ID_ID,
	STR_DLG_PATIENT_AGE,
	STR_DLG_PATIENT_AGE_AGE,
	STR_DLG_PATIENT_GESTATIONAL,
	STR_DLG_PATIENT_GESTATIONAL_WEEK,
	STR_DLG_PATIENT_GESTATIONAL_DAY,
	STR_DLG_PATIENT_GTIMES,
	STR_DLG_PATIENT_GTIMES_TIMES,
	STR_DLG_PATIENT_NOTE,
	STR_DLG_PATIENT_NOTE_PAD,
	STR_DLG_PATIENT_EDIT,
	STR_DLG_PATIENT_SAVE,
	STR_DLG_PATIENT_LIST_NAME,
	STR_DLG_PATIENT_LIST_ID,
	STR_DLG_PATIENT_LIST_TIME,
	STR_DLG_PATIENT_LIST_ITEM0,
	STR_DLG_PATIENT_LIST_ITEM1,
	STR_DLG_PATIENT_LIST_ITEM2,
	STR_DLG_PATIENT_LIST_ITEM3,
	STR_DLG_PATIENT_LIST_ITEM4,
	STR_DLG_PATIENT_LIST_ITEM5,
	STR_DLG_PATIENT_LIST_ITEM6,
	STR_DLG_PATIENT_LIST_ITEM7,
	STR_DLG_PATIENT_LIST_ITEM8,
	STR_DLG_PATIENT_LIST_ITEM9,

	STR_DLG_NEW_PATIENT,
	STR_DLG_NEW_PATIENT_OTHER,
	STR_DLG_NEW_PATIENT_INFO,
	STR_DLG_NEW_PATIENT_CANCEL,
	STR_DLG_NEW_PATIENT_BACK,
	STR_DLG_NEW_PATIENT_NEXT,
	STR_DLG_NEW_PATIENT_BUILD,
	STR_DLG_NEW_PATIENT_WARNING1,
	STR_DLG_NEW_PATIENT_WARNING2,
	STR_DLG_NEW_PATIENT_WARNING3,

	STR_DLG_PNT_RECALL_MANAGER,
	STR_DLG_PNT_RECALL_ALL,
	STR_DLG_PNT_RECALL_NAME,
	STR_DLG_PNT_RECALL_ID,
	STR_DLG_PNT_RECALL_OPEN,
	STR_DLG_PNT_RECALL_DELETE,
	STR_DLG_PNT_RECALL_PNAME0,
	STR_DLG_PNT_RECALL_PNAME1,
	STR_DLG_PNT_RECALL_PNAME2,
	STR_DLG_PNT_RECALL_PNAME3,
	STR_DLG_PNT_RECALL_PNAME4,
	STR_DLG_PNT_RECALL_PNAME5,
	STR_DLG_PNT_RECALL_PNAME6,
	STR_DLG_PNT_RECALL_PNAME7,
	STR_DLG_PNT_RECALL_PNAME8,
	STR_DLG_PNT_RECALL_PNAME9,
	STR_DLG_PNT_RECALL_PID0,
	STR_DLG_PNT_RECALL_PID1,
	STR_DLG_PNT_RECALL_PID2,
	STR_DLG_PNT_RECALL_PID3,
	STR_DLG_PNT_RECALL_PID4,
	STR_DLG_PNT_RECALL_PID5,
	STR_DLG_PNT_RECALL_PID6,
	STR_DLG_PNT_RECALL_PID7,
	STR_DLG_PNT_RECALL_PID8,
	STR_DLG_PNT_RECALL_PID9,
	
	STR_DLG_RECALL_CAPTION,
	STR_DLG_RECALL_TIME,
	STR_DLG_RECALL_INFO,
	STR_DLG_RECALL_ENDTIME,
	STR_DLG_RECALL_LENGTH,
	STR_DLG_RECALL_PRINT_PAGE,
	STR_DLG_RECALL_PRINT_ALL,

	// $$##字符键盘的字符串
	STR_DLG_CHAR_A,
	STR_DLG_CHAR_B,
	STR_DLG_CHAR_C,
	STR_DLG_CHAR_D,
	STR_DLG_CHAR_E,
	STR_DLG_CHAR_F,
	STR_DLG_CHAR_G,
	STR_DLG_CHAR_H,
	STR_DLG_CHAR_I,
	STR_DLG_CHAR_J,
	STR_DLG_CHAR_K,
	STR_DLG_CHAR_L,
	STR_DLG_CHAR_M,
	STR_DLG_CHAR_N,
	STR_DLG_CHAR_O,
	STR_DLG_CHAR_P,
	STR_DLG_CHAR_Q,
	STR_DLG_CHAR_R,
	STR_DLG_CHAR_S,
	STR_DLG_CHAR_T,
	STR_DLG_CHAR_U,
	STR_DLG_CHAR_V,
	STR_DLG_CHAR_W,
	STR_DLG_CHAR_X,
	STR_DLG_CHAR_Y,
	STR_DLG_CHAR_Z,
	STR_DLG_CHAR_0,
	STR_DLG_CHAR_1,
	STR_DLG_CHAR_2,
	STR_DLG_CHAR_3,
	STR_DLG_CHAR_4,
	STR_DLG_CHAR_5,
	STR_DLG_CHAR_6,
	STR_DLG_CHAR_7,
	STR_DLG_CHAR_8,
	STR_DLG_CHAR_9,
	STR_DLG_CHAR_SPACE,
	STR_DLG_CHAR_DEL,
	STR_DLG_CHAR_OK,
	STR_DLG_CHAR_ESC,
	STR_DLG_CHAR_MINUS,
	STR_DLG_CHAR_DOT,
	STR_DLG_CHAR_NUM_MARK,
	STR_DLG_CHAR_IME,
	STR_DLG_CHAR_MARK,
	STR_DLG_CHAR_COMMA,	 //逗号
	STR_DLG_CHAR_CAPS,
	STR_DLG_KB_PY_PRE,
	STR_DLG_KB_PY_NEXT,
	STR_DLG_KB_PY_CHAR1,
	STR_DLG_KB_PY_CHAR2,
	STR_DLG_KB_PY_CHAR3,
	STR_DLG_KB_PY_CHAR4,
	STR_DLG_KB_PY_CHAR5,
	STR_DLG_KB_PY_CHAR6,
	STR_DLG_KB_PY_CHAR7,
	STR_DLG_KB_PY_CHAR8,
	STR_DLG_KB_CAPTION,
	STR_DLG_KB_INPUT,
	STR_DLG_KB_TIPS,
	STR_DLG_PASSWD_OK,
	STR_DLG_PASSWD_CANCEL,
	STR_DLG_PASSWD_CAPTION,
	STR_DLG_PASSWD1_CAPTION,
	STR_DLG_PASSWD2_CAPTION,
	STR_DLG_PASSWD3_CAPTION,
	STR_DLG_PASSWD4_CAPTION,
	STR_DLG_PASSWD_TIPS,
	STR_DLG_PASSWD_ERROR,
	STR_DLG_SETDATETIME,
	STR_DLG_SETDATE,
	STR_DLG_SETTIME,
	STR_DLG_SETUP,
	STR_DLG_SETUP_FETAL,
	STR_DLG_SETUP_PRINT,
	STR_DLG_SETUP_PRINTER,
	STR_DLG_SETUP_SYSTEM,
	STR_DLG_SETUP_DATETIME,
	STR_DLG_SETUP_ALARM,

	STR_DLG_SETUP_ALM_VOL,
	STR_DLG_SETUP_KEY_VOL,
	STR_DLG_SETUP_FASTPRINT,
	STR_DLG_SETUP_SPEED,
	STR_DLG_SETUP_TIMER,
	STR_DLG_SETUP_AUTOPRINT,
	STR_DLG_SETUP_PRINTTYPE,
	STR_DLG_SETUP_PRINTCONTRAST,

	STR_DLG_SETUP_SET_FM,
	STR_DLG_SETUP_PRINT_B,
	STR_DLG_SETUP_PRINTER_B,
	STR_DLG_SETUP_NETWORK_B,
	STR_DLG_SETUP_NETWORK,
	STR_DLG_SETUP_DEMO,
	STR_DLG_SETUP_DEMO_EXIT,

	STR_DLG_SETUP_PRINT_PAGE,
	STR_DLG_SETUP_PRINT_PAGESTART,
	STR_DLG_SETUP_PRINT_CURR,

	STR_DLG_SETUP_DEFAULT,

	STR_DLG_NIGHT_MODE,
	STR_DLG_EXIT_NIGHT_MODE,

	STR_DLG_NET_AUTOLINK,
	STR_DLG_NET_IPADDR,
	STR_DLG_NET_MASK,
	STR_DLG_NET_GATEWAY,
	STR_DLG_NET_SERVERIP,
	STR_DLG_NET_PORT,
	STR_DLG_NET_HWADDR,
	STR_DLG_NET_SERVER,

	STR_DLG_ANALY_FUNC,
	STR_DLG_ANALY_VALID,
	STR_DLG_ANALY_COLLECT,
	STR_DLG_ANALY_BUILD,
	STR_DLG_ANALY_AUTO,
	STR_DLG_ANALY_RESTART,
	STR_DLG_ANALY_DONE,
	STR_DLG_ANALY_SHOW,
	STR_DLG_ANALY_RESULT,
	STR_DLG_ANALY_SAVE,
	STR_DLG_ANALY_PRINT,
	STR_DLG_ANLS_ITEMS,
	STR_DLG_ANLS_FHR_BASE,
	STR_DLG_ANLS_AMPLITUDE,
	STR_DLG_ANLS_FAST_TIME,
	STR_DLG_ANLS_FAST_AMPL,
	STR_DLG_ANLS_FM_TIMES,
	STR_DLG_ANLS_RESULT,
	STR_DLG_ANLS_SCORE,
	STR_DLG_ANLS_NAME,
	STR_DLG_ANLS_TIME,
	STR_DLG_ANLS_VALID,
	STR_DLG_ANLS_TOCO,
	STR_DLG_ANLS_ANALYSIS_RESULT,
	STR_DLG_ANLS_DIAGNOSIS,
	STR_DLG_ANLS_DATAONLYREFERENCE,
	STR_DLG_ANLS_SIGNATURE,
	STR_DLG_ANLS_DATE,

	STR_DLG_05MIN,
	STR_DLG_10MIN,
	STR_DLG_15MIN,
	STR_DLG_20MIN,
	STR_DLG_30MIN,
	STR_DLG_40MIN,
	STR_DLG_50MIN,
	STR_DLG_60MIN,
	STR_DLG_50PERCENT,
	STR_DLG_75PERCENT,
	STR_DLG_100PERCENT,

	STR_DLG_PRINTER_FHR60,
	STR_DLG_PRINTER_FHR210,
	STR_DLG_PRINTER_FHRMIN,
	STR_DLG_PRINTER_FHRMAX,
	STR_DLG_PRINTER_TOCO100,
	STR_DLG_PRINTER_TOCO0,
	STR_DLG_PRINTER_SCALE,
	STR_DLG_PRINTER_SELFTEST,
	STR_DLG_PRINTER_30,
	STR_DLG_PRINTER_60,
	STR_DLG_PRINTER_90,
	STR_DLG_PRINTER_180,
	STR_DLG_PRINTER_210,
	STR_DLG_PRINTER_240,

	STR_DLG_STATUS,
	STR_DLG_STATUS_INFO1,
	STR_DLG_STATUS_INFO2,
	STR_DLG_STATUS_INFO3,
	STR_DLG_STATUS_INFO4,
	STR_DLG_STATUS_INFO5,
	STR_DLG_STATUS_INFO6,
	STR_DLG_STATUS_INFO7,
	STR_DLG_STATUS_INFO8,
	STR_DLG_STATUS_INFO9,

	STR_DLG_STATUS_AC,
	STR_DLG_STATUS_DC,
	STR_DLG_STATUS_CHARGING,
	STR_DLG_STATUS_FULLCHARGED,
	STR_DLG_STATUS_NOBATT,
	STR_DLG_STATUS_BATTPOWER,
	STR_DLG_STATUS_NETWORKRUNNING,
	STR_DLG_STATUS_NETWORKDISCONN,
	STR_DLG_STATUS_PRINTER,
	STR_DLG_STATUS_ALARM,

	STR_DLG_SYSSETUP,
	STR_DLG_SYSSETUP_B,
	STR_DLG_SYSSETUP_COLOR,
	STR_DLG_SYSSETUP_COLOR_B,
	STR_DLG_SYSSETUP_LANGUAGE,
	STR_DLG_SYSSETUP_LANGUAGE_B,

	STR_DLG_LANGUAGE_CHOICE,
	STR_DLG_DATE_FORMAT,
	STR_DLG_DATE_DELIMITER,
	STR_DLG_TIME_FORMAT,
	STR_DLG_LANGUAGE_ENGLISH,
	STR_DLG_LANGUAGE_CHINESE,
	STR_DLG_LANGUAGE_RUSSIAN,
	STR_DLG_LANGUAGE_SPANISH,
	STR_DLG_LANGUAGE_TURKISH,
	STR_DLG_DATE_FORMAT_YMD,
	STR_DLG_DATE_FORMAT_MDY,
	STR_DLG_DATE_FORMAT_DMY,
	STR_DLG_DATE_FORMAT_HMS,
	STR_DLG_DATE_FORMAT_HM,
	STR_DLG_DATE_FORMAT_THMS,
	STR_DLG_DATE_FORMAT_THM,
	STR_DLG_DATE_DELIMITER1,
	STR_DLG_DATE_DELIMITER2,
	STR_DLG_DATE_DELIMITER3,
	
	STR_DLG_FACTORY_MAINTAIN_B,
	STR_DLG_FACTORY_MAINTAIN,
	STR_DLG_FACTORY_MONITORTYPE,
	STR_DLG_FACTORY_ARTEMIS4S,
	STR_DLG_FACTORY_ARTEMIS2,
	STR_DLG_FACTORY_ENBTOUCH,
	STR_DLG_FACTORY_RECORDERTYPE,
	STR_DLG_FACTORY_REC_112,
	STR_DLG_FACTORY_REC_150,
	STR_DLG_FACTORY_REC_SETUP,
	STR_DLG_FACTORY_UPDATE,
	STR_DLG_FACTORY_ANALY_ENABLE,
	STR_DLG_FACTORY_ANALY_DISABLE,
	STR_DLG_FACTORY_VERSION,

	STR_DLG_ABOUT_B,
	STR_DLG_ABOUT,
	STR_DLG_ABOUT_TIME,
	STR_DLG_ABOUT_START,
	STR_DLG_ABOUT_VERSION,
	STR_DLG_ABOUT_VERSION_NUM,
	STR_DLG_ABOUT_COMPILE_TIME,
	STR_DLG_ABOUT_COMPILE_DATE,
	STR_DLG_ABOUT_COMPANY,

	STR_DLG_COLOR,
	STR_DLG_MAINTAIN_B,
	STR_DLG_MAINTAIN,
	STR_ENABLE_HELP_STRING,
	STR_DISABLE_HELP_STRING,

	STR_WINSTR_MAX = STR_DISABLE_HELP_STRING,

//$$$$$$$$$$系统报警字符串开始$$$$$$$$$$$$//
	STR_ALM_FIRST,
	//fetal params
	STR_ALM_PHS_FIRST = STR_ALM_FIRST,
	STR_ALM_FHR1_TOO_HI = STR_ALM_PHS_FIRST,
	STR_ALM_FHR1_TOO_LO,
	STR_ALM_FHR2_TOO_HI,
	STR_ALM_FHR2_TOO_LO,
	STR_ALM_PHS_MAX = STR_ALM_FHR2_TOO_LO,

	STR_ALM_TECH_FIRST,
	STR_ALM_FETAL_INIT_ERROR = STR_ALM_TECH_FIRST,
	STR_ALM_FHR1_LOW_SIGNAL,
	STR_ALM_FHR2_LOW_SIGNAL,
	STR_ALM_FETAL_COMM_ERR,
	STR_ALM_FETAL_COMM_STOP,
	STR_ALM_FHR_ALM_LMT_ERR,
	STR_ALM_FHR1_EXCEED,
	STR_ALM_FHR2_EXCEED,
	STR_ALM_TOCO_EXCEED,
	STR_ALM_FHR1_SENSOR_OFF,
	STR_ALM_FHR2_SENSOR_OFF,
	STR_ALM_TOCO_SENSOR_OFF,
	STR_ALM_FM_SENSOR_OFF,
	STR_ALM_KEYBOARD_INIT_ERR,
	STR_ALM_KEYBOARD_NOT_AVAILABLE,
	STR_ALM_KEYBOARD_COMM_ERR,
	STR_ALM_POWER_5V_TOO_HIGH,
	STR_ALM_POWER_5V_TOO_LOW,
	STR_ALM_POWER_12V_TOO_HIGH,
	STR_ALM_POWER_12V_TOO_LOW,
	STR_ALM_POWER_3V_TOO_HIGH,
	STR_ALM_POWER_3V_TOO_LOW,
	STR_ALM_POWER_BATTERY_LOW,
	STR_ALM_BATTREY_20_MINUTES,
	STR_ALM_BATTREY_10_MINUTES,
	STR_ALM_BATTERY_VOL_TOO_HIGH,
	STR_ALM_BATTERY_VOL_TOO_LOW,
	STR_ALM_PRINTER_HIGH_CURRENT,
	STR_ALM_PRINTER_HEAD_HOT,
	STR_ALM_PRINTER_DOOR_NOT_CLOSED,
	STR_ALM_PRINTER_PAPER_OUT,
	STR_ALM_PRINTER_SERIAL_ERR,
	STR_ALM_PRINTER_NOT_AVAILABLE,
	STR_ALM_TECH_MAX,
	STR_ALM_END = STR_ALM_TECH_MAX,
//$$$$$$$$$$系统报警字符串结束$$$$$$$$$$$$//
	STR_HELP_FIRST,
	STR_HELP_TECH_ALARM_INFO = STR_HELP_FIRST,
	STR_HELP_PHYS_ALARM_INFO,
	STR_HELP_SYSTEM_STATUS,
	STR_HELP_PATIENT_SETUP,
	STR_HELP_CHANGE_FACE,
	STR_HELP_SYSTEM_MENU,
	STR_HELP_DATETIME_SETUP,
	STR_HELP_ENTER_VIEW_WAVE,
	STR_HELP_EXIT_VIEW_WAVE,
	STR_HELP_FETAL_WAVE_MOVE_LEFT,
	STR_HELP_FETAL_WAVE_MOVE_RIGHT,
	STR_HELP_END = STR_HELP_FETAL_WAVE_MOVE_RIGHT,
	STR_REC_FIRST,
	STR_REC_END = STR_REC_FIRST,
	STR_DLG_ANLS_BASE_LINE,
	STR_DLG_ANLS_AMPLITUDE_VAR,
	STR_DLG_ANLS_PERIOD_VAR,
	STR_DLG_ANLS_ACCELRATION,
	STR_DLG_ANLS_SLOWDOWN,
	STR_DLG_ANLS_SLOWDOWN_TYPE0,
	STR_DLG_ANLS_SLOWDOWN_TYPE1,
	STR_DLG_ANLS_SLOWDOWN_TYPE2,
	STR_DLG_ANLS_ACCELRATION_TYPE0,
	STR_DLG_ANLS_ACCELRATION_TYPE1,
	STR_DLG_ANLS_ACCELRATION_TYPE2,
	STR_DLG_ANLS_NST,
	STR_DLG_ANLS_FISCHER,
	STR_DLG_ANLS_KREBS,
	STR_DLG_ANLS_CST,
	STR_DLG_ANLS_FETALMOVIE,
	STR_DLG_ANLS_NOTHING,
	STR_DLG_ANLS_NOTHINGORED,
	STR_DLG_ANLS_LDOROTHER,
	STR_DLG_ANLS_CHANGE,
	STR_DLG_ANLS_EDSLOW,
	STR_DLG_ANLS_LASTSLOW,
	
	STR_ALL_STR

} STRINGID;

#define  STR_MAXNUM	STR_ALL_STR

#ifndef WINSTR_GLOBALS
#define WINSTR_EXT extern
#else
#define WINSTR_EXT 
#endif
WINSTR_EXT CHAR  * GlobalStr[];
WINSTR_EXT char gMonitorUUID[37];

// 函数声明
WINSTR_EXT BOOL  InitGlobalString( INT8 language );
WINSTR_EXT BOOL  ReInitGlobalStrPtr (INT8 language);
WINSTR_EXT VOID  GetLanguageFile(const char *dir_src);
WINSTR_EXT BOOL  SaveLanguageFile(INT8 lan);

#define LoadString(str_id)	(GlobalStr[str_id])

//目前系统的控件的字符串全部是在这里静态分配的.在向buffer写数据时需要检查是否溢出.
#define GetWinStrLen(str_id)   (150)  // 总是最大长度
#define TestWinStrLen(len, str_id)   ASSERT_REPORT(1)  // 总是对的.

#endif
